### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by yahmad3495** [spadmanaban25/cse15l-lab-report#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
    -Be sure to include all the necessary URLs like the link to download VSCode
- [x] All relevant code examples written with backticks (```)
    -Make sure that all of the code/commands are formatted correctly with backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
     -please include what you tried in lab 1: Use what you’ve learned to come up with the quickest process you can for making a 
      local edit to WhereAmI.java, then copying it to the remote server and running it. 
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job overall! Feel free to comment below any questions related to the feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by spadmanaban25** [comment]
Hello Younus,

I wanted to clarify on the backticks grade. I am a bit confused on having all code/commands formatted with backticks?

**Comment by yahmad3495** [comment]
Hello! By properly formatted commands we just mean that wherever you have some code examples (like ssh, scp, and others) they should be formatted as code in markdown. This would mean changing the screenshots of the command in the terminal you included to writing the command like this: `` command ``.

**Comment by spadmanaban25** [comment]
Ok, so basically I have to replace the screenshots with a body of code that contains commands (sssh, scp, etc.) that should be embedded directly into the markdown code? Similar to how the commands are presented in the Week 1 Lab Tasks from CSE15L Course Website?

**Comment by yahmad3495** [comment]
Yep exactly! And also include how many keystrokes it takes for your procedure to optimizing runtime part of the report (last section).

**Comment by spadmanaban25** [comment]
Ok thank you. For the keystrokes section, is typing part of it? If so, how I determine typing as part of number of keystrokes?

**Comment by yahmad3495** [comment]
Yeh you can assume that typing out the command will be a part of the process so one way to do it just to see how many characters the command is which will give you the # of keystrokes you need. You could also include a timer to note how long it takes.

**Comment by spadmanaban25** [comment]
Ok, just wanted to know the maximum number of keystrokes to have when typing the scp and ssh commands? Sorry to disturb you with the questions.

**Comment by yahmad3495** [comment]
All good no worries! It's totally okay to keep asking questions. I don't think there is a specific amount we're looking for when it comes to the keystroke, you can sort of estimate it.

**Comment by spadmanaban25** [comment]
Ok thanks, so I know tapping one key on the keyboard is a keystroke. On the course website for lab 1, it was mentioning that I needed to keep under 10 keystrokes for calling multiple commands. I was wondering how would it be possible if I was to type out the scp and ssh commands (along with account name ...@ieng6.ucsd.edu)? Is it assumed that I should have that stored on my command history and just use the up arrow when actually counting the number of keystrokes?

**Comment by yahmad3495** [comment]
Hello, sorry I wasn't able to respond to your comment earlier. And yes you can assume you have it stored in your command history as well!

**Comment by spadmanaban25** [comment]
Thanks for helping me understand the errors.
