### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by yukatig** [spadmanaban25/cse15l-lab-report#3]
Here is your feedback for Lab Report 3 - Streamlining `ssh` Configuration:

- [x] Show your `.ssh/config` file, and how you edited it (with VScode, another program, etc)
- [x] Show the `ssh` command logging you into your account using just the alias you chose.
- [x] Show an `scp` command copying a file to your account using just the alias you chose.

Additional comments from your grader:

To make signing in even more streamlined, I would check out Part 6 in Lab 1, but other than that good job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by spadmanaban25** [comment]
Thanks for the feedback Yukati, I actually configured the ssh keys feature on my local computer, but after sometime like a week or so, it "forgets" and will ask me to enter password when signing in. To fix this, I have to always configure ssh keys. But anyways thank you.

**Comment by yukatig** [comment]
Got it! No worries then :) Really nice job with the report.
